site_name: Curtis Mayberry
site_url: https://Curtisma.org
repo_url: https://github.com/curtisma/curtisma.github.io
repo_name: 'GitHub'
site_description: Curtis Mayberry's home page, portfolio, and blog
site_author: Curtis Mayberry

nav:
  - index.md
  - Projects:
    - projects/index.md
    - projects/cicc-panels-oshic/cicc_panel_oschic.md
  - Blog:
    - blog/index.md
  - Cascode-Labs: http://www.cascode-labs.org/

theme:
  name: material
  features:
    - navigation.tabs

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - social
  - blog
