authors:
  Curtisma:
    name: Curtis Mayberry
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/4685385?s=400&u=1b91fe9e81b5881818c958651d472f7b4e00a40a&v=4
    url: https://github.com/Curtisma
